### PR TITLE
this looks much better!

### PR DESCRIPTION
**Pull request by gregwebs**

### CODE REVIEW

**Comment by gregwebs** [comment]
this pull request is now picking up other changes on my branch. Be wary or the 1.9 fix- that may break 1.8

**Comment by fhwang** [comment]
Hi Greg,

Thanks for your contribution. Can you submit changes along with test cases so I can get a better sense of what sort of use-cases you're trying to satisfy? And generally it's worth noting that I need to be sort of a stickler about changes w/o tests -- in my experience a project like this can get super-buggy super-fast if changes come without tests.

Thanks,
Francis

**Comment by gregwebs** [comment]
I was confused about testing because I didn't see any test folders. I am looking at it more closely, and it appears that you only do integration tests on pre-generated Rails applications. Is it alright if I write some unit tests?

**Comment by fhwang** [comment]
Yeah, the testing's sort of unorthodox: I should probably add a note to the README about that. Anyway, yes, the testing is through the rails apps, contained in rails_3_0 and rails_3_1 ... you can run an individual test file/case by cd'ing into that directory, running bundle install, and then running one of the integration tests as if you were just dev'ing your own Rails app. To run the entire test suite, type "rake" at the root of the project.

Generally speaking, I think integration tests are the way to go on this stuff, since it integrates so tightly with the Rails controller/view layer. IMO this is part of the problem activescaffold had: It tried to skimp on full-stack testing, but then the bugs crept in so viciously that after a while you didn't even know which Github fork to use. So if you could stick with integration tests for the time being, that would be much appreciated.

Thanks,
Francis

**Comment by gregwebs** [comment]
please add a note to the README about testing. Given that this is integration level testing, I shouldn't actually have to write new tests. The tests just need to be made so they can also run against mongoid. This is not as hard as it sounds. Mostly it means that instead of 

``` ruby
BlogPost.find_by_title title
```

It should stick to:

``` ruby
BlogPost.where(:title => title).first
```

Then I just need some way to swap out the models. I am considering changing this:

``` ruby
class Comment < ActiveRecord::Base
```

into

``` ruby
class Comment < ModelClass
```

where ModelClass would be changed depending if the test is for activerecord or mongoid. I would add Mongoid field declarations, but that would be a no-op for ActiveRecord.

**Comment by fhwang** [comment]
I'll add info about testing to the documentation site at some point. Generally speaking, you should be able to type "rake" in the root of the admin_assistant directory and it should run. You may have to cd into one of the rails app directories and do a rake db:migrate (as if devv'ing a Rails app). Let me know how that works out for you.

Generally speaking, though, I'm choosing to be fairly strict about contributions and tests, and I do think this is a case where you'll need some integration tests to test out specifically how admin_assistant runs with both Mongoid and AR. It's not realistic to make admin_assistant Mongoid-only, so if it's going to support both Mongoid and AR, it needs to have tests for both as well. Maybe that sounds like a hassle, but if you've ever used a library with a lot of contributors that's really buggy, it's probably because it was too loose about its contributions. I've seen that happen with lots of libraries and I'd prefer to avoid it with this one.

Also: I've recently updated will_paginate in master as well -- you may want to a merge or rebase from my master before going much further.

**Comment by gregwebs** [comment]
will_paginate completely breaks mongoid. On my branch I have switched to Kaminari which works with MongoDB. From what I have seen Kaminari is as good or better than will_paginate in every possible aspect. I didn't update the ActiveRecord part because it seems like you are jumping through some strange hoops to use will_paginate properly and I am not sure what is going on there. Please cherry-pick my Kaminari commits and move ActiveRecord over to Kaminari.

**Comment by gregwebs** [comment]
I added the testing explanation to the README along with an overview of rails admins.

**Comment by gregwebs** [comment]
Oh, I also added a require 'delegate' which fixed the broken tests.

I must not have explained my comment about testing well- I was trying to go over how the tests can be made to work against both ActiveRecord and Mongoid. As it currently stands I can't run tests against the existing ActiveRecord tests until it is switched to Kaminari.

**Comment by fhwang** [comment]
So, a few notes:
1. It's going to be easier for me to accept documentation patches if they're to the website (http://fhwang.github.com/admin_assistant/) than to the README. It's going to be confusing to users if we have documentation split between two places.
2. I'm open to the idea generally of supporting Mongoid, and I think the idea that you could re-use a lot of the existing code to get good test coverage is an intriguing one. I'm looking forward to hearing how that works out for you. But however it gets done, admin_assistant needs to keep its core support of ActiveRecord, which means that any changes to the test suite needs to leave the AR testing in place as well. It doesn't look like your code is doing that yet?
3. Pull requests are generally easier to accept if they are for discrete, granular changes, and unfortunately this pull request is a pretty messy one judged by those standards. Can we close this one out, with the possibility of future, more focused pull requests?

Francis

**Comment by gregwebs** [comment]
1) I see the README as where someone gets the overview and decides if they
want to use the project and the site designed more for those that are
already using it. Either way you should switch to using a .md file that
looks much nicer. Perhaps README content should also be on the documentation
site.
2) The only change I made to the tests is to use Arel style finds that are
compatible with Mongoid
3) will_paginate is a major blocker right now. I have commits here to switch
over to Kaminari, but not for ActiveRecord. So I think the starting point is
that you switch the ActiveRecord part to Kaminari, or at least tell me that
you think it is a good idea and will review and cleanup an attempt at a
patch from me. I can submit a pull request fo just for the Kaminari part of
this pull request.

BTW, there is a gem orm_adapter that we might consider using to simplify
things.

**Comment by fhwang** [comment]
1. I think then we disagree on what READMEs vs web pages are for. For the time being I believe the web page should be for everything -- if you're thinking of using the library, if you're a Rails newbie who wants to get started, if you're experienced with Rails and want to get started, and if you're looking for full-fledged API reference. There's already been a lot of time spent on the web site, and I'd hate to diminish that by splitting documentation.
2. I guess w.r.t. Mongoid support the ultimate requirement is this: I need to type one command and run the test suite against both AR and Mongoid at the same time. If you can wire that up then I'd love to take a look at it.
3. I don't have time to switch to Kaminari, or even to evaluate in comparison to will_paginate. I don't really have a strong opinion of one over the other, but will_paginate works for AR now so there's that. (And FWIW it seems like will_paginate has become a lot more active in the past few months, perhaps because of the healthy competition from Kaminari.) I guess I'd say, if Kaminari can be used in admin_assistant in a way that all the tests pass for AR, then I could be persuaded. But I don't have the time to try doing that myself.

**Comment by fhwang** [comment]
I'm going to close those pull request for now. I actually have a bit more time to do admin_assistant work than back in October, but going forward it would be a lot easier for me to deal with these if the pull requests were smaller and more focused. Thanks!

**Comment by gregwebs** [comment]
I was willing to make smaller and more focused pull requests if I had been given any sign from you that you would have pulled them in. Refusing to switch to Kaminari blocked any progress on this.

admin_assistant is tied to AcitveRecord. If puffer (which uses orm_adapter) was available when I started, that would have been a much better choice: you should point MongoDB users there.

**Pull request closed without merging**
